name: finetuning_alexnet
channels:
- pytorch
- nvidia
- defaults
dependencies:
- pytorch=2.4.0
- torchaudio=2.4.0
- torchvision=0.19.0
- pytorch-cuda=11.8
- python=3.12.4
- pip=24.0
- pip:
  - scikit-learn==1.5.1
  - matplotlib==3.9.1
  - jupyterlab==4.2.4
  
